/**
 * Paths emitted into `public/sitemap.xml` by `npm run sitemap`.
 * Keep in sync with public routes and `reactSnap.include` in package.json.
 */
import { PACK20_ARTICLES } from "../data/blogs/pack20/catalog.js";

const PACK20_SITEMAP_ENTRIES = PACK20_ARTICLES.map((article) => ({
  path: article.path,
  lastmod: "2026-05-23",
  changefreq: "monthly",
  priority: "0.7",
}));

export const SITEMAP_URL_ENTRIES = [
  { path: "/", lastmod: "2026-04-26", changefreq: "weekly", priority: "1.0" },
  { path: "/about", lastmod: "2026-04-26", changefreq: "monthly", priority: "0.8" },
  { path: "/contact", lastmod: "2026-04-26", changefreq: "monthly", priority: "0.7" },
  { path: "/free-reputation-scan", lastmod: "2026-05-15", changefreq: "monthly", priority: "0.85" },
  { path: "/ai-reputation-scan", lastmod: "2026-05-19", changefreq: "monthly", priority: "0.85" },
  { path: "/case-studies", lastmod: "2026-04-26", changefreq: "monthly", priority: "0.8" },
  {
    path: "/case-studies/executive-and-founder-reputation-management",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/financial-professional-reputation-recovery",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/medical-and-healthcare-reputation-management",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/hr-and-employment-dispute-reputation-management",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/e-commerce-and-retail-brand-recovery",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/consumer-electronics-product-crisis-recovery",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/startup-reputation-recovery-after-funding-controversy",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/e-commerce-brand-recovery-after-counterfeit-allegations",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-review-that-almost-ended-the-surgeons-career",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-gp-and-the-misattributed-article",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-litigation-partner-and-the-losing-verdict",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-family-lawyer-and-the-client-vendetta",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-ifa-and-the-collapsed-investment-fund",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-accountant-and-the-wrongful-dismissal-headline",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-graduate-and-the-incident-that-followed-him-online",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/case-studies/the-senior-product-manager-and-the-glassdoor-problem",
    lastmod: "2026-04-26",
    changefreq: "monthly",
    priority: "0.75",
  },
  { path: "/services", lastmod: "2026-04-26", changefreq: "monthly", priority: "0.9" },
  { path: "/who-we-serve", lastmod: "2026-05-15", changefreq: "monthly", priority: "0.85" },
  {
    path: "/who-we-serve/individual",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/who-we-serve/financial-advisors",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/who-we-serve/executives-and-c-suite-leaders",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.8",
  },
  {
    path: "/who-we-serve/doctors-and-healthcare-professionals",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/who-we-serve/lawyers-and-attorneys",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/who-we-serve/job-seekers",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.75",
  },
  {
    path: "/who-we-serve/businesses-and-companies",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.8",
  },
  { path: "/blog", lastmod: "2026-04-26", changefreq: "weekly", priority: "0.7" },
  {
    path: "/blog/how-to-suppress-negative-content-professionals-guide",
    lastmod: "2026-05-15",
    changefreq: "monthly",
    priority: "0.7",
  },
  {
    path: "/blog/diy-online-reputation-management-complete-guide",
    lastmod: "2026-05-20",
    changefreq: "monthly",
    priority: "0.7",
  },
  {
    path: "/blog/remove-negative-search-results-from-google",
    lastmod: "2026-05-22",
    changefreq: "monthly",
    priority: "0.7",
  },
  {
    path: "/blog/how-long-does-it-take-to-fix-online-reputation",
    lastmod: "2026-05-22",
    changefreq: "monthly",
    priority: "0.7",
  },
  {
    path: "/blog/can-you-remove-news-articles-from-google-search",
    lastmod: "2026-05-22",
    changefreq: "monthly",
    priority: "0.7",
  },
  ...PACK20_SITEMAP_ENTRIES,
  { path: "/resources/guide", lastmod: "2026-04-26", changefreq: "monthly", priority: "0.7" },
  { path: "/resources/faqs", lastmod: "2026-04-26", changefreq: "monthly", priority: "0.6" },
  { path: "/privacy-policy", lastmod: "2026-05-15", changefreq: "yearly", priority: "0.4" },
  { path: "/terms-of-service", lastmod: "2026-05-15", changefreq: "yearly", priority: "0.4" },
  { path: "/cookie-policy", lastmod: "2026-05-15", changefreq: "yearly", priority: "0.4" },
  { path: "/refund-policy", lastmod: "2026-05-15", changefreq: "yearly", priority: "0.4" },
  {
    path: "/acceptable-use-policy",
    lastmod: "2026-05-15",
    changefreq: "yearly",
    priority: "0.4",
  },
  { path: "/terms-of-use", lastmod: "2026-05-15", changefreq: "yearly", priority: "0.4" },
  {
    path: "/dmca-copyright-policy",
    lastmod: "2026-05-15",
    changefreq: "yearly",
    priority: "0.4",
  },
];
